// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const authLockQueue = new Map<string, Promise<unknown>>();

async function appLocalAuthLock<R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> {
  const name = _name || 'supabase-auth';
  const previous = authLockQueue.get(name) ?? Promise.resolve();

  const current = previous
    .catch(() => undefined)
    .then(fn)
    .finally(() => {
      if (authLockQueue.get(name) === current) {
        authLockQueue.delete(name);
      }
    });

  authLockQueue.set(name, current);
  return current;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    lock: appLocalAuthLock,
  }
});
